### ISSUE TITLE
The example project from the Quick start quide not working out of the box

### ISSUE THREAD

**Issue by GeraltOnTheRoach** [materna-se/fegen#3]
The Backend will escape throwing an error without spring security package. There is a bean in FeGen, that requires security classes:
![2021-04-25 18_27_56-fegen-demo – build gradle (backend)](https://user-images.githubusercontent.com/51488315/116001464-dccda500-a5f4-11eb-938b-3506107f6fda.png)

After adding spring security the requests will be responded with 401 by default.
![2021-04-25 18_28_35-FeGen Demo - Firefox Developer Edition](https://user-images.githubusercontent.com/51488315/116001466-de976880-a5f4-11eb-898a-4466cd2a8275.png)

**Comment by c-classen** [comment]
I think you stumbled upon a known issue that was fixed in this commit:

https://github.com/materna-se/fegen/commit/5688149f7c9c87ed43f3edba2008ddbb8546dc9a#diff-22c5f512a340edd6f79e9f18d8b3962857d9310dde827e060f5b2715c50bae43R30

As you can see, in the develop branch, reflection is used to determine whether Spring Security is available and only activate security features if it is, thereby avoiding the NoClassDefFoundError.

However, no new version of fegen has been released since that commit. If you don't want to wait for a new release, you can build fegen by running `git clone --recurse-submodules https://github.com/materna-se/fegen.git` and then executing `./gradlew publishToMavenLocal` within the `fegen` directory.

To use that version, you will need to add `mavenLocal()` to the two `repositories` sections of your `build.gradle` (The one within `buildscript` and the one outside of it). Instead of running `npm install @materna-se/fegen-runtime`, you will also need to add a line like the following to your `package.json` and execute `npm install`:

```
 "@materna-se/fegen-runtime": "../../relative/path/to/fegen/fegen-web/fegen-web-runtime"
```

**Comment by GeraltOnTheRoach** [comment]
Hi Clemens, thank you for a quick and detailed response.
